name = 'nfc-public-deploy'
main = "index.js"
compatibility_date = "2024-12-01"
workers_dev = true


[[kv_namespaces]]
binding = "DEVELOP_USERS"
id = "6d4adf0217c148b0bb17fecb17da9bef"
preview_id = "6d4adf0217c148b0bb17fecb17da9bef"
